const { Router } = require("express")
const UserController = require("./users/user.controller")
const AuthController = require('./auth/auth.controller')
const PostController = require('./posts/post.controller')
const router = Router()

router
    .get('/user', UserController.GET_USER)
    .get('/users', UserController.ALL_USER)
    .get('/otherUser/:userId', UserController.OTHER_USER_PROFILE)
    .get('/userFound', UserController.FOUND_USER)
    .get('/posts', PostController.GET)
    .get('/getlikes', PostController.GET_POST_LIKES)
    .post('/likesuser', PostController.GET_POST_LIKES_USER)
    .post('/likes', PostController.POST_LIKES)
    .post('/posts', PostController.POST)
    .get('/comment/:postId', PostController.GET_COMMENTS)
    .post('/comment', PostController.POST_COMMENT)
    .post('/profile', UserController.POST_PROFILE)
    .post('/userRegester', AuthController.REGESTER_USER)
    .post('/userLogin', AuthController.LOGIN_USER)
    .get('/getlogin', AuthController.GET_LOGIN)
    .post('/followers', PostController.POST_FOLLOWING)
    .get('/followers/:userId', UserController.GET_FOLLOWERS)
    .post('/user/bio', UserController.ADD_BIO)
module.exports = router